FROM node:12

WORKDIR /usr/src/api

RUN npm install -g nodemon

COPY package*.json ./

ENV NEW_RELIC_NO_CONFIG_FILE=true \
    NEW_RELIC_LICENSE_KEY=0d7815592d30303a508f8fa2c996fcc793afNRAL \
    NEW_RELIC_APP_NAME="chat-api" \
    NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true \
    NEW_RELIC_LOG=stdout

RUN npm install

COPY . .